name: mb_prj_1
description: "BMI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/logo_1.png

  fonts:
    - family: WorkSans
      fonts:
        - asset: asset/fonts/WorkSans-VariableFont_wght.ttf
          style: normal